# Generated by Django 3.2.4 on 2022-03-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_group', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=255)),
            ],
            options={
                'verbose_name': 'Ledger Category',
                'verbose_name_plural': 'Ledger Categories',
            },
        ),
        migrations.CreateModel(
            name='Ledger_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('category', models.CharField(max_length=255, null=True)),
                ('primary_group', models.CharField(max_length=255, null=True)),
                ('grand_parent', models.CharField(max_length=255, null=True)),
                ('parent', models.CharField(max_length=255, null=True)),
                ('ledger', models.CharField(max_length=255)),
                ('opening_balance', models.FloatField(default=0, null=True)),
                ('closing_balance', models.FloatField(default=0, null=True)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ledger Master',
                'verbose_name_plural': 'Ledger Masters',
            },
        ),
        migrations.CreateModel(
            name='Voucher_BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('voucher_key', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('voucher_date', models.DateField()),
                ('ledger', models.CharField(max_length=255)),
                ('ledger_master_id', models.IntegerField()),
                ('ledger_alter_id', models.IntegerField()),
                ('ledger_category', models.CharField(max_length=255, null=True)),
                ('ledger_primary_group', models.CharField(max_length=255, null=True)),
                ('ledger_grand_parent', models.CharField(max_length=255, null=True)),
                ('ledger_parent', models.CharField(max_length=255, null=True)),
                ('bank_date', models.DateField(null=True)),
                ('transaction_type', models.CharField(max_length=255, null=True)),
                ('instrument_number', models.CharField(max_length=255, null=True)),
                ('instrument_amount', models.FloatField()),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher BankDetail',
                'verbose_name_plural': 'Voucher BankDetails',
            },
        ),
        migrations.CreateModel(
            name='Voucher_Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('voucher_key', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('voucher_date', models.DateField()),
                ('ledger', models.CharField(max_length=255)),
                ('ledger_master_id', models.IntegerField()),
                ('ledger_alter_id', models.IntegerField()),
                ('ledger_category', models.CharField(max_length=255, null=True)),
                ('ledger_primary_group', models.CharField(max_length=255, null=True)),
                ('ledger_grand_parent', models.CharField(max_length=255, null=True)),
                ('ledger_parent', models.CharField(max_length=255, null=True)),
                ('bill_name', models.CharField(max_length=255, null=True)),
                ('bill_type', models.CharField(max_length=255, null=True)),
                ('bill_amount', models.FloatField()),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher Bill',
                'verbose_name_plural': 'Voucher Bills',
            },
        ),
        migrations.CreateModel(
            name='Voucher_CostCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('voucher_key', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('voucher_date', models.DateField()),
                ('ledger', models.CharField(max_length=255)),
                ('ledger_master_id', models.IntegerField()),
                ('ledger_alter_id', models.IntegerField()),
                ('ledger_category', models.CharField(max_length=255, null=True)),
                ('ledger_primary_group', models.CharField(max_length=255, null=True)),
                ('ledger_grand_parent', models.CharField(max_length=255, null=True)),
                ('ledger_parent', models.CharField(max_length=255, null=True)),
                ('cc_category', models.CharField(max_length=255, null=True)),
                ('cc_name', models.CharField(max_length=255, null=True)),
                ('cc_amount', models.FloatField()),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher CostCenter',
                'verbose_name_plural': 'Voucher CostCenters',
            },
        ),
        migrations.CreateModel(
            name='Voucher_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('voucher_key', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('voucher_type', models.CharField(max_length=255)),
                ('voucher_view', models.CharField(max_length=255)),
                ('create_date', models.DateField()),
                ('create_time', models.TimeField()),
                ('alter_date', models.DateField()),
                ('alter_time', models.TimeField()),
                ('narrations', models.CharField(max_length=500, null=True)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher Detail',
                'verbose_name_plural': 'Voucher Details',
            },
        ),
        migrations.CreateModel(
            name='Voucher_Ledgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('voucher_key', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('voucher_date', models.DateField()),
                ('ledger', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('ledger_master_id', models.IntegerField()),
                ('ledger_alter_id', models.IntegerField()),
                ('ledger_category', models.CharField(max_length=255, null=True)),
                ('ledger_primary_group', models.CharField(max_length=255, null=True)),
                ('ledger_grand_parent', models.CharField(max_length=255, null=True)),
                ('ledger_parent', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher Ledger',
                'verbose_name_plural': 'Voucher Ledgers',
            },
        ),
        migrations.CreateModel(
            name='VoucherTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher Type',
                'verbose_name_plural': 'Voucher Types',
            },
        ),
        migrations.CreateModel(
            name='Tally_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tally_begin_date', models.DateField()),
                ('tally_port', models.IntegerField(default=9000)),
                ('account_id', models.EmailField(help_text='Registered AccountID of Tally', max_length=254)),
                ('computer_name', models.CharField(help_text='Name of the computer where tdl and tally is running. Please see system settings to get computer name.', max_length=255)),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_organization', to='users.organization')),
                ('valid_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tally Detail',
                'verbose_name_plural': 'Tally Details',
                'unique_together': {('name', 'account_id')},
            },
        ),
    ]
