# Generated by Django 3.2.4 on 2022-05-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_Category',
        ),
    ]
