# Generated by Django 3.2.4 on 2021-07-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_detail',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_organization', to='users.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='tally_detail',
            unique_together={('name', 'account_id')},
        ),
    ]
