# Generated by Django 3.2.4 on 2021-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tally_detail_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_detail',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
