# Generated by Django 3.2.4 on 2021-07-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('alter_id', models.IntegerField()),
                ('voucher_key', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('voucher_date', models.DateField()),
                ('ledger', models.CharField(max_length=255)),
                ('ledger_master_id', models.IntegerField()),
                ('ledger_alter_id', models.IntegerField()),
                ('ledger_category', models.CharField(max_length=255, null=True)),
                ('ledger_primary_group', models.CharField(max_length=255, null=True)),
                ('ledger_grand_parent', models.CharField(max_length=255, null=True)),
                ('ledger_parent', models.CharField(max_length=255, null=True)),
                ('bill_name', models.CharField(max_length=255)),
                ('bill_type', models.CharField(max_length=255)),
                ('bill_amount', models.FloatField()),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Voucher Bill',
                'verbose_name_plural': 'Voucher Bills',
            },
        ),
    ]
