# Generated by Django 3.2.4 on 2022-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_custom_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_group', models.CharField(max_length=255, null=True)),
                ('primary_group', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Custom Ledger Group',
                'verbose_name_plural': 'Custom Ledger Groups',
            },
        ),
    ]
