# Generated by Django 3.2.4 on 2021-06-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organization_name'),
        ('dashboard', '0002_tally_details_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_details',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_organization', to='users.organization'),
        ),
    ]
