# Generated by Django 3.2.4 on 2021-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_voucher_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_bills',
            name='bill_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucher_bills',
            name='bill_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
