# Generated by Django 3.2.4 on 2021-06-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organization_name'),
        ('dashboard', '0003_alter_tally_details_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tally_Details',
            new_name='Tally_Detail',
        ),
    ]
