# Generated by Django 3.2.4 on 2021-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_tally_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_detail',
            name='tally_begin_date',
            field=models.DateField(),
        ),
    ]
