# Generated by Django 3.2.4 on 2021-07-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tally_detail_tally_begin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_detail',
            name='account_id',
            field=models.EmailField(help_text='Registered AccountID of Tally', max_length=254, unique=True),
        ),
    ]
