# Generated by Django 3.2.4 on 2022-05-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_custom_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_Category',
        ),
    ]
