# Generated by Django 3.2.4 on 2021-07-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tally_detail_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_detail',
            name='account_id',
            field=models.EmailField(help_text='Registered AccountID of Tally', max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='tally_detail',
            unique_together={('name', 'account_id', 'computer_name')},
        ),
    ]
