# Generated by Django 3.2.4 on 2021-07-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210711_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tally_detail',
            unique_together={('name', 'account_id')},
        ),
    ]
